[package]
name = "stream-check-rust"
version = "0.1.0"
authors = ["segler <segler_alex@web.de>"]

[dependencies]
url = "1.7.0"
native-tls = "0.1.5"
threadpool = "1.7.1"
hostname = "*"
mysql = "*"
colored = "*"
av-stream-info-rust = "0.4.0"
clap = "2.31.2"
website-icon-extract = "0.3.0"
reqwest = "0.8.5"